name: Second Workflow
on: workflow_dispatch
jobs:
  second-job:
    runs-on: macos-12
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye !"
